### ISSUE TITLE
Ap-sta project issue

### ISSUE THREAD

**Issue by Simon-L** [willemwouters/EMW3162_WICED#3]
Hi,
first off, thanks a lot for your great work!
I have been using the ESP8266 for a wifi-connected device project for a while now but the EM3162 looks like a much better solution since you've put all this to work together: full GCC toolchain, documented tools (openocd, WICED sdk) rather than the weird "MICO" thing they advretise for it...

I have finally managed to flash the device with your explanation.
The trickiest part for me was the hardware part ie. finding the right pins to switch the factory firmware to update mode and then figuring out how to use openocd and the BusPirate. Your code compiled perfectly, without a hitch. (I had to set the buspirate in normal speed mode)

The "problem" I have now is to figure out what the code does, I can't see any new AP from my laptop.
From looking at the code it seems it starts an AP and connects as client (looking at `config_wifi_dct.h`) with hardcoded details. That file is commented in `the apsta.c` file though.
Anyway, I'm sure there are just a few details to figure out in the code for me to really start hacking this little big guy!

Thanks again, and please do give us some updates about your progress and new projects with the EMW3162!
I thought maybe as we go forward we could start some kind of community around the chip (just like ESP8266) if it is in fact a great product and enough interest gathers around it.

**Comment by willemwouters** [comment]
Hi.

First just a quick response via my mobile. Will answer in more details soon.

But the dct file is compiled in a different stage. First is the bootloader
, then the dct image(which hold info like wlan) and the main image.

So the changes in config_wifi_dct.c is compiled during dct image creation.

Did you flash all 3 images?

Which project did you use? The EMW3162 or EMW3162_wiced?

Greetings willem

**Comment by Simon-L** [comment]
Good evening

I used the `ap-sta` project from EMW3162_WICED.
I followed the instruction in the README, cd'ed to projects/ap-sta/ and then make.
Then I used `make download_bin` to flash the images since I noted the `make download` command uses the `jlink.cfg` file instead which is not what I have. I'm using a Bus Pirate.
To answer your question, looking at the `Makefile` it seems it flashes 3 images.

What is the ap-sta code supposed to do? I guess I should change some things to fit my setup, like the client mode SSID.
Is it normal that this line here is commented out?
https://github.com/willemwouters/EMW3162_WICED/blob/master/projects/ap-sta/src/apsta.c#L5

Do you use IRC?
Or maybe Gitter.im for the repo?
You can find me on IRC as FergusL in #esp8266 channel on Freenode.

What is your programmer hardware?
I have a bunch of ST boards like Discovery and Nucleo.
I'd like to use these as programmers for the EMW3162, I know it's possible, just need to figure out the right options to put in the OpenOCD cfg file.

**Comment by willemwouters** [comment]
Hi,

That should be the correct project,
The EMW3162_WICED was created from the original EMW3162 (this is the
original WICED Broadcom project with adjustments for emw3162)
I created the project so I could have a bit more control over my build
enviroment, and to split the build process in separate libraries, so i
could easy reuse compontents.

Honestly it has been a while since i last compiled the ap-sta project, but
it should work. Lately im playing with an arduino audio board, getting the
raw audio samples over SPI and sending them in packages to my laptop
playing them on gstreamer(the audioboard project)
And it has also been a while since i flashed the DCT image, while i was not
changing anything in my wifi part there was no need to flash the dct.

the ap-sta part is the real main part, it sets your wifi in the mode you
want(ap/client) and will grab the details of you configuration from the DCT
image(as far i know)

Always good is to have a blinking led example, then you know for sure your
code is running. Or put some breakpoints in gdb via your jtag
programmer(buspirate). I will search if i have a blinky project available
for you.

I use the J-Link programmer, bought is somewhere from china(8$) because it
is compatible to the EMB-380 developer board. I previously also used the
buspirate as JTAG. Placed some pictures here:
http://hackaday.io/project/4128-emw3162
Still need to fill in the page further, but the pictures are there.
When using the EMB-380 board with the jlink everything is need and tidy ;)

The line should be commented out, because i had no reference to any
variables in it. The broadcom software(some where in the code) itself reads
this information from the DCT memory area.

I also have a Discovery board around somewhere, used it once for blinky led
;)
I will try out the ap-sta project again, check if all files are in sync
etc, and i'll let you know. But in my setup I have an open Wifi network
called WICED Soft Ap.

Greetings Willem

On Mon, Mar 9, 2015 at 9:43 PM, Simon L. <notifications@github.com> wrote:

> Good evening
>
> I used the ap-sta project from EMW3162_WICED.
> I followed the instruction in the README, cd'ed to projects/ap-sta/ and
> then make.
> Then I used make download_bin to flash the images since I noted the make
> download command uses the jlink.cfg file instead which is not what I
> have. I'm using a Bus Pirate.
> To answer your question, looking at the Makefile it seems it flashes 3
> images.
>
> What is the ap-sta code supposed to do? I guess I should change some
> things to fit my setup, like the client mode SSID.
> Is it normal that this line here is commented out?
>
> https://github.com/willemwouters/EMW3162_WICED/blob/master/projects/ap-sta/src/apsta.c#L5
>
> Do you use IRC?
> Or maybe Gitter.im for the repo?
> You can find me on IRC as FergusL in #esp8266 channel on Freenode.
>
> What is your programmer hardware?
> I have a bunch of ST boards like Discovery and Nucleo.
> I'd like to use these as programmers for the EMW3162, I know it's
> possible, just need to figure out the right options to put in the OpenOCD
> cfg file.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/willemwouters/EMW3162_WICED/issues/3#issuecomment-77938097>
> .
>



-- 
Groetjes Willem Wouters

**Comment by willemwouters** [comment]
Ohh, and i opened a gitter.im
https://gitter.im/willemwouters/EMW3162_WICED


On Mon, Mar 9, 2015 at 9:43 PM, Simon L. <notifications@github.com> wrote:

> Good evening
>
> I used the ap-sta project from EMW3162_WICED.
> I followed the instruction in the README, cd'ed to projects/ap-sta/ and
> then make.
> Then I used make download_bin to flash the images since I noted the make
> download command uses the jlink.cfg file instead which is not what I
> have. I'm using a Bus Pirate.
> To answer your question, looking at the Makefile it seems it flashes 3
> images.
>
> What is the ap-sta code supposed to do? I guess I should change some
> things to fit my setup, like the client mode SSID.
> Is it normal that this line here is commented out?
>
> https://github.com/willemwouters/EMW3162_WICED/blob/master/projects/ap-sta/src/apsta.c#L5
>
> Do you use IRC?
> Or maybe Gitter.im for the repo?
> You can find me on IRC as FergusL in #esp8266 channel on Freenode.
>
> What is your programmer hardware?
> I have a bunch of ST boards like Discovery and Nucleo.
> I'd like to use these as programmers for the EMW3162, I know it's
> possible, just need to figure out the right options to put in the OpenOCD
> cfg file.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/willemwouters/EMW3162_WICED/issues/3#issuecomment-77938097>
> .
>



-- 
Groetjes Willem Wouters

**Comment by willemwouters** [comment]
I cleaned the WICED_SRC and ap-sta. Recompiled WICED_SRC/build.sh and ap-sta.
Reflashed all 3 images via make download. WiFi Ap shows up on my laptop, called WICED Soft Ap.
When connecting i get an ip, and when i browser to 192.168.0.1 i see my test page.
Everything is looking fine here.

**Comment by Simon-L** [comment]
I compiled OpenOCD 0.8.0 to get better buspirate support but it still did not work.
I have the most recent version of the BP firmware and bootloader.
After all this it became completely unusable so I wouldn't declare it as a viable solution.
(The slow speed and lack of NJTRST are two key points here for the failure of this otherwise neat little toy)

I went ahead on the ST Link front and managed to get the embedded ST Link on two boards I own to work with EMW3162, ST Link v2-1 on Nucleo and ST Link v2 on Discovery, I used OpenOCD.
I still have some unresolved issues about JTAG[1] but it does not keep me from downloading code to the chip and the ap-sta project is working all as intended. You can now close this issue.
I'll add wiki pages about ST Link.

Thanks a lot for your support!
Anyone interested please join us in the Gitter chat! https://gitter.im/willemwouters/EMW3162_WICED

[1] Error is : `Error: jtag status contains invalid mode value - communication failure` either caused by unconnected or wrongly connected wires or sleep mode while debugging that prevent the debugger from talking to the MCU. I'll open a separate issue about this but the error itself is a good starting googling point :)))
